import type {
  BudgetAdoptionRequest,
  BudgetOperation,
  BudgetPreview,
  NativeBudgetPolicy,
} from "#/api/budget-service/budget-service.types";
import type { OrgBudgetSettings } from "#/api/organization-service/organization-service.api";

export const adoptionRequest: BudgetAdoptionRequest = {
  preview_fingerprint: "a".repeat(64),
  idempotency_key: "reviewed-request",
  current_team_allowance: 100,
  current_default_member_allowance: 0,
  current_member_allowances: { "member-1": null },
  future_monthly_limit: 700,
  future_default_member_limit: 80,
  future_member_limits: { "member-1": 90 },
  reset_day: 15,
  replace_native_reset_schedules: true,
};

export const pendingOperation: BudgetOperation = {
  operation_id: "operation-1",
  operation_generation: 1,
  kind: "adopt",
  status: "pending",
  control_mode: "needs_adoption",
  generation: 1,
  error: "Not yet verified",
  created_at: "2026-09-14T12:00:00Z",
  finished_at: null,
  current_allowances: {
    team: 100,
    default_member: 0,
    members: { "member-1": null },
  },
  future_policy: {
    monthly_limit: 700,
    default_user_monthly_limit: 80,
    member_limits: { "member-1": 90 },
    reset_day: 15,
  },
  cycle_end_at: "2026-09-15T00:00:00Z",
  team_block: { initial: false, target: false, budget_owned: false },
};

const nativePolicy: NativeBudgetPolicy = {
  max_budget: 1000,
  soft_budget: null,
  budget_duration: null,
  budget_reset_at: null,
  models: ["budget-test"],
  allowed_models: null,
  blocked: false,
  rpm_limit: 20,
  tpm_limit: null,
  max_parallel_requests: null,
  has_additional_budget_windows: false,
  has_model_budgets: false,
};

export const budgetPreview: BudgetPreview = {
  control_mode: "needs_adoption",
  generation: 0,
  fingerprint: adoptionRequest.preview_fingerprint,
  observed_at: "2026-09-14T12:00:00Z",
  pending_operation_id: null,
  team_spend: 589.6945274540012,
  team_policy: nativePolicy,
  default_member_policy: nativePolicy,
  members: [
    {
      user_id: "member-1",
      in_organization: true,
      lifetime_spend: 100,
      enforcement_spend: 10,
      max_budget: 1000,
      counter_source: "membership",
      budget_source: "private_member",
      budget_duration: null,
      budget_reset_at: null,
      policy: nativePolicy,
    },
  ],
  keys: [{ user_id: "member-1", policy: { ...nativePolicy, max_budget: 50 } }],
};

export const managedBudget: OrgBudgetSettings = {
  control_mode: "managed",
  control_generation: 1,
  pending_operation_id: null,
  current_cycle_allowance: 100,
  current_cycle_default_member_allowance: 10,
  current_cycle_member_allowances: { "off-page": 0 },
  future_member_limits: { "off-page": 100 },
  enabled: true,
  monthly_limit: 700,
  default_user_monthly_limit: 80,
  reset_day: 15,
  litellm_last_sync_at: "2026-09-14T12:00:00Z",
  litellm_last_sync_status: "success",
  litellm_last_sync_error: null,
  reconciliation_state: "healthy",
  reconciliation_error: null,
  desired_team_max_budget: 689.6945274540012,
  applied_team_max_budget: 689.6945274540012,
  budget_policy_matches: true,
  applied_at: "2026-09-14T12:00:00Z",
  applied_policy_observed_at: "2026-09-14T12:00:00Z",
  slack_channel: null,
  slack_team_id: null,
  cycle_start_at: "2026-09-14T12:00:00Z",
  cycle_end_at: "2026-09-15T00:00:00Z",
  spend_status: "live",
  spend_observed_at: "2026-09-14T12:01:00Z",
  current_spend: 20,
  current_spend_percentage: 20,
  unmapped_spend: 0,
  unmapped_member_count: 0,
  thresholds: [],
  users: [
    {
      user_id: "member-1",
      user_name: "Member One",
      user_email: "member@example.test",
      current_spend: 2,
      monthly_limit: null,
      effective_monthly_limit: 10,
      is_disabled: false,
      is_override: false,
    },
  ],
  users_total: 2,
  users_page: 1,
  users_per_page: 1,
};
