import type { HubIntegration } from "#/types/integrations-hub";

/** Official Hub catalog from @openhands/extensions, ordered by popularity. */
export const OFFICIAL_HUB_CATALOG: Array<
  Omit<HubIntegration, "connected" | "enabled">
> = [
  {
    slug: "github",
    name: "GitHub",
    description:
      "Search code, manage issues and pull requests, and inspect repos via the GitHub API.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "GitHub",
    kind: "Engineering",
    tools: [],
    notes:
      "Current managed connector works with bearer tokens today; GitHub OAuth is a strong candidate for a future one-click connect flow.",
    categories: ["Engineering", "Source control"],
    docsUrl: "https://github.com/github/github-mcp-server",
    logoUrl: "https://cdn.simpleicons.org/github/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://api.githubcopilot.com/mcp/",
    oauthConfig: {
      authorizationUrl: "https://github.com/login/oauth/authorize",
      tokenUrl: "https://github.com/login/oauth/access_token",
      scopes: ["read:user", "repo"],
    },
  },
  {
    slug: "gitlab",
    name: "GitLab",
    description:
      "Repositories, merge requests, issues, and pipelines via the GitLab API.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "GitLab",
    kind: "Engineering",
    tools: [],
    notes:
      "Reconnects legacy Settings > Integrations GitLab tokens. Works with gitlab.com OAuth; self-managed hosts can use a personal access token.",
    categories: ["Engineering", "Source control"],
    docsUrl: "https://docs.gitlab.com/ee/api/oauth2.html",
    logoUrl: "https://cdn.simpleicons.org/gitlab/FFFFFF",
    connectorProvider: "http",
    apiBaseUrl: "https://gitlab.com/api/v4",
    oauthConfig: {
      authorizationUrl: "https://gitlab.com/oauth/authorize",
      tokenUrl: "https://gitlab.com/oauth/token",
      scopes: ["read_user", "read_api", "read_repository"],
    },
  },
  {
    slug: "azure_devops",
    name: "Azure DevOps",
    description:
      "Repos, pull requests, and work items in Azure DevOps organizations.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Azure DevOps",
    kind: "Engineering",
    tools: [],
    notes:
      "Reconnects legacy Settings > Integrations Azure DevOps PATs. Prefer a personal access token with Code and Work Items scopes.",
    categories: ["Engineering", "Source control"],
    docsUrl:
      "https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/pats",
    logoUrl: "https://cdn.simpleicons.org/azuredevops/FFFFFF",
    connectorProvider: "http",
    apiBaseUrl: "https://dev.azure.com",
  },
  {
    slug: "forgejo",
    name: "Forgejo",
    description:
      "Self-hosted Git forges compatible with the Forgejo / Gitea API.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Forgejo",
    kind: "Engineering",
    tools: [],
    notes:
      "Reconnects legacy Settings > Integrations Forgejo tokens. Point the connector at your Forgejo host and use an access token.",
    categories: ["Engineering", "Source control"],
    docsUrl: "https://forgejo.org/docs/latest/user/api-usage/",
    logoUrl: "https://cdn.simpleicons.org/forgejo/FFFFFF",
    connectorProvider: "http",
  },
  {
    slug: "bitbucket_data_center",
    name: "Bitbucket Data Center",
    description:
      "Self-managed Bitbucket Data Center repositories, PRs, and projects.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Bitbucket Data Center",
    kind: "Engineering",
    tools: [],
    notes:
      "Reconnects legacy Settings > Integrations Bitbucket Data Center credentials. Uses a personal access token against your DC host.",
    categories: ["Engineering", "Source control"],
    docsUrl:
      "https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html",
    logoUrl: "https://cdn.simpleicons.org/bitbucket/FFFFFF",
    connectorProvider: "http",
  },
  {
    slug: "jira-dc",
    name: "Jira Data Center",
    description:
      "Self-managed Jira Data Center issues, projects, and workflows.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Jira Data Center",
    kind: "Project management",
    tools: [],
    notes:
      "Reconnects legacy Settings > Integrations Jira Data Center installs. Configure your DC base URL and an API token or PAT.",
    categories: ["Project management", "Engineering"],
    docsUrl:
      "https://confluence.atlassian.com/adminjiraserver/using-personal-access-tokens-1026032368.html",
    logoUrl: "https://cdn.simpleicons.org/jira/FFFFFF",
    connectorProvider: "http",
  },
  {
    slug: "slack",
    name: "Slack",
    description:
      "Read channels, post messages, and search workspace history from your agent.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Slack",
    kind: "Communication",
    tools: [],
    notes:
      "The OAuth option uses Slack's official hosted MCP server (confidential OAuth user-token auth); the local option runs the open-source zencoderai stdio server with a bot token.",
    categories: ["Communication", "Operations"],
    docsUrl: "https://github.com/zencoderai/slack-mcp-server",
    logoUrl:
      "https://cdn.jsdelivr.net/gh/OpenHands/extensions/integrations/icons/slack.svg",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.slack.com/mcp",
    oauthConfig: {
      authorizationUrl: "https://slack.com/oauth/v2_user/authorize",
      tokenUrl: "https://slack.com/api/oauth.v2.user.access",
      scopes: [
        "search:read.public",
        "search:read.private",
        "search:read.mpim",
        "search:read.im",
        "search:read.files",
        "search:read.users",
        "chat:write",
        "channels:history",
        "groups:history",
        "mpim:history",
        "im:history",
        "canvases:read",
        "canvases:write",
        "users:read",
        "users:read.email",
      ],
      clientAuthentication: "body",
    },
  },
  {
    slug: "tavily",
    name: "Tavily",
    description:
      "Production-grade web search optimized for LLM agents. Free tier available.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Tavily",
    kind: "Integration",
    tools: [],
    docsUrl: "https://github.com/tavily-ai/tavily-mcp",
    connectorProvider: "mcp",
  },
  {
    slug: "atlassian",
    name: "Atlassian (Jira & Confluence)",
    description:
      "Search Jira issues, manage tickets, and read Confluence pages from your agent.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Atlassian (Jira & Confluence)",
    kind: "Project management",
    tools: [],
    categories: ["Project management", "Documentation"],
    docsUrl: "https://mcp-atlassian.soomiles.com/docs/installation",
    logoUrl: "https://cdn.simpleicons.org/atlassian/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.atlassian.com/v1/mcp",
  },
  {
    slug: "linear",
    name: "Linear",
    description:
      "Browse and update Linear issues, cycles, and projects from the agent.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Linear",
    kind: "Project management",
    tools: [],
    notes:
      "Popular among modern product engineering teams and already useful to this repo's users.",
    categories: ["Project management", "Engineering"],
    docsUrl: "https://linear.app/docs/mcp",
    logoUrl: "https://cdn.simpleicons.org/linear/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.linear.app/mcp",
    oauthConfig: {
      authorizationUrl: "https://mcp.linear.app/authorize",
      tokenUrl: "https://mcp.linear.app/token",
      scopes: ["read", "write"],
      clientAuthentication: "none",
      registrationUrl: "https://mcp.linear.app/register",
    },
  },
  {
    slug: "notion",
    name: "Notion",
    description:
      "Read and edit Notion pages, databases, and blocks via Notion's MCP server.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Notion",
    kind: "Knowledge base",
    tools: [],
    categories: ["Knowledge base", "Documentation"],
    docsUrl: "https://developers.notion.com/docs/mcp",
    logoUrl: "https://cdn.simpleicons.org/notion/000000",
    connectorProvider: "http",
    apiBaseUrl: "https://api.notion.com",
    openApiUrl: "https://developers.notion.com/openapi.json",
    oauthConfig: {
      authorizationUrl: "https://api.notion.com/v1/oauth/authorize",
      tokenUrl: "https://api.notion.com/v1/oauth/token",
    },
  },
  {
    slug: "vanta",
    name: "Vanta",
    description:
      "Query Vanta compliance controls, tests, evidence, risks, and vulnerabilities from the agent.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Vanta",
    kind: "Security",
    tools: [],
    notes:
      "Vanta's hosted remote MCP server (beta, requires a Vanta Admin role). Regional endpoints: US https://mcp.vanta.com/mcp, EU https://mcp.eu.vanta.com/mcp, AUS https://mcp.aus.vanta.com/mcp. Authentication is OAuth only - no API keys.",
    categories: ["Security", "Compliance"],
    docsUrl: "https://developer.vanta.com/docs/vanta-mcp",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.vanta.com/mcp",
    oauthConfig: {
      authorizationUrl: "https://app.vanta.com/oauth/authorize",
      tokenUrl: "https://api.vanta.com/oauth/token",
      scopes: ["mcp-api.all:read"],
      optionalScopes: ["mcp-api.all:write"],
      clientAuthentication: "none",
      registrationUrl: "https://api.vanta.com/oauth/register",
    },
  },
  {
    slug: "ordinal",
    name: "Ordinal",
    description:
      "Social media posts, profiles, analytics, labels, approvals, and engagements.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Ordinal",
    kind: "Social media",
    tools: [],
    notes:
      "Official MCP server backed by Ordinal's API with API-key (Bearer) auth.",
    categories: ["Social media", "Marketing"],
    docsUrl: "https://docs.tryordinal.com/api/mcp",
    logoUrl: "https://app.tryordinal.com/favicon.ico",
    connectorProvider: "mcp",
    serverUrl: "https://app.tryordinal.com/api/mcp",
  },
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    description:
      "Generate speech, clone voices, and transcribe audio via ElevenLabs.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "ElevenLabs",
    kind: "Audio",
    tools: [],
    notes:
      "Official API-key connector backed by ElevenLabs' published OpenAPI spec.",
    categories: ["Audio", "AI"],
    docsUrl: "https://elevenlabs.io/docs/api-reference/mcp",
    logoUrl: "https://cdn.simpleicons.org/elevenlabs/FFFFFF",
    connectorProvider: "http",
    apiBaseUrl: "https://api.elevenlabs.io",
    openApiUrl: "https://api.elevenlabs.io/openapi.json",
  },
  {
    slug: "bitbucket",
    name: "Bitbucket",
    description:
      "Repositories, pull requests, and Atlassian engineering workflows.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Bitbucket",
    kind: "Engineering",
    tools: [],
    notes:
      "Popular in Atlassian-centric teams and complements Jira/Confluence.",
    categories: ["Engineering", "Source control"],
    docsUrl: "https://developer.atlassian.com/cloud/bitbucket/oauth-2/",
    connectorProvider: "http",
    apiBaseUrl: "https://api.bitbucket.org/2.0",
    openApiUrl:
      "https://developer.atlassian.com/cloud/bitbucket/swagger.v3.json",
    oauthConfig: {
      authorizationUrl: "https://bitbucket.org/site/oauth2/authorize",
      tokenUrl: "https://bitbucket.org/site/oauth2/access_token",
      scopes: ["account", "repository"],
    },
  },
  {
    slug: "xero",
    name: "Xero",
    description: "Accounting, contacts, invoices, and bookkeeping workflows.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Xero",
    kind: "Finance",
    tools: [],
    notes: "Important accounting platform in many regions.",
    categories: ["Finance", "Accounting"],
    docsUrl: "https://developer.xero.com/documentation/guides/oauth2/overview/",
    connectorProvider: "http",
    apiBaseUrl: "https://api.xero.com/api.xro/2.0",
    openApiUrl:
      "https://api.apis.guru/v2/specs/xero.com/xero_accounting/2.9.4/openapi.json",
    oauthConfig: {
      authorizationUrl: "https://login.xero.com/identity/connect/authorize",
      tokenUrl: "https://identity.xero.com/connect/token",
      scopes: ["accounting.contacts.read"],
    },
  },
  {
    slug: "quickbooks",
    name: "QuickBooks",
    description:
      "Accounting, invoices, customers, and financial operations via the QuickBooks Online MCP server.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "QuickBooks",
    kind: "Finance",
    tools: [],
    notes:
      "Official Intuit QuickBooks Online MCP server runs locally over stdio after a one-time OAuth handshake.",
    categories: ["Finance", "Accounting"],
    docsUrl: "https://github.com/intuit/quickbooks-online-mcp-server",
    logoUrl: "https://cdn.simpleicons.org/quickbooks/FFFFFF",
    connectorProvider: "mcp",
  },
  {
    slug: "okta",
    name: "Okta",
    description: "Identity, users, applications, and access administration.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Okta",
    kind: "Identity",
    tools: [],
    notes: "High-value admin and security automation surface.",
    categories: ["Identity", "Enterprise"],
    docsUrl:
      "https://developer.okta.com/docs/guides/implement-oauth-for-okta/main/",
    connectorProvider: "http",
    apiBaseUrl: "https://{yourOktaDomain}/api/v1",
    openApiUrl:
      "https://raw.githubusercontent.com/okta/okta-sdk-java/master/src/swagger/api.yaml",
    oauthConfig: {
      authorizationUrl: "https://{yourOktaDomain}/oauth2/v1/authorize",
      tokenUrl: "https://{yourOktaDomain}/oauth2/v1/token",
      scopes: ["okta.users.read"],
    },
  },
  {
    slug: "netlify",
    name: "Netlify",
    description: "Sites, builds, deploy previews, and web operations.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Netlify",
    kind: "Deployment",
    tools: [],
    notes: "Common alternative hosting/deployment automation target.",
    categories: ["Deployment", "Developer tools"],
    docsUrl: "https://docs.netlify.com/api/get-started/#oauth-applications",
    connectorProvider: "http",
    apiBaseUrl: "https://api.netlify.com/api/v1",
    openApiUrl:
      "https://raw.githubusercontent.com/netlify/open-api/master/swagger.yml",
    oauthConfig: {
      authorizationUrl: "https://app.netlify.com/authorize",
      tokenUrl: "https://api.netlify.com/oauth/token",
      scopes: ["sites:read"],
    },
  },
  {
    slug: "vercel",
    name: "Vercel",
    description:
      "Deployments, projects, domains, and preview environment workflows.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Vercel",
    kind: "Developer tools",
    tools: [],
    notes: "Especially relevant to this repo's deployment model.",
    categories: ["Developer tools", "Deployment"],
    docsUrl: "https://vercel.com/docs/rest-api#oauth-apps",
    connectorProvider: "http",
    apiBaseUrl: "https://api.vercel.com",
    openApiUrl: "https://api.apis.guru/v2/specs/vercel.com/0.0.1/openapi.json",
    oauthConfig: {
      authorizationUrl: "https://vercel.com/oauth/authorize",
      tokenUrl: "https://api.vercel.com/v2/oauth/access_token",
      scopes: ["project:read"],
    },
  },
  {
    slug: "supabase",
    name: "Supabase",
    description:
      "Query and manage your Supabase project, including database, auth, and storage.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Supabase",
    kind: "Database",
    tools: [],
    notes:
      "Popular developer platform with broad automation value and a documented management-API OAuth integration flow.",
    categories: ["Database", "Developer tools"],
    docsUrl: "https://supabase.com/docs/guides/getting-started/mcp",
    logoUrl: "https://cdn.simpleicons.org/supabase/FFFFFF",
    connectorProvider: "mcp",
  },
  {
    slug: "posthog",
    name: "PostHog",
    description: "Product analytics, feature flags, and session insights.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "PostHog",
    kind: "Analytics",
    tools: [],
    notes: "Relevant for product analytics and experimentation workflows.",
    categories: ["Analytics", "Product"],
    docsUrl: "https://posthog.com/docs/model-context-protocol",
    logoUrl: "https://cdn.simpleicons.org/posthog/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.posthog.com/mcp",
  },
  {
    slug: "sentry",
    name: "Sentry",
    description:
      "Triage issues, inspect events, and run Seer fixes against your Sentry org.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Sentry",
    kind: "Observability",
    tools: [],
    notes: "Natural target for engineering support agents.",
    categories: ["Observability", "Engineering"],
    docsUrl: "https://docs.sentry.io/product/sentry-mcp/",
    logoUrl: "https://cdn.simpleicons.org/sentry/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.sentry.dev/mcp",
    oauthConfig: {
      authorizationUrl: "https://sentry.io/oauth/authorize",
      tokenUrl: "https://sentry.io/oauth/token",
      scopes: ["project:read", "event:read", "org:read"],
    },
  },
  {
    slug: "datadog",
    name: "Datadog",
    description:
      "Logs, metrics, monitors, incidents, and observability workflows.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Datadog",
    kind: "Observability",
    tools: [],
    notes:
      "Uses Datadog's official hosted MCP server. The MCP endpoint host is site-specific: use https://mcp.<site>.datadoghq.com/v1/mcp for your Datadog site (e.g. mcp.us5.datadoghq.com for US5). The default URL below targets US1 and can be edited in the install dialog.",
    categories: ["Observability", "Operations"],
    docsUrl: "https://docs.datadoghq.com/mcp_server/setup/",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.datadoghq.com/v1/mcp",
    oauthConfig: {
      authorizationUrl: "https://app.datadoghq.com/oauth2/v1/authorize",
      tokenUrl: "https://api.datadoghq.com/oauth2/v1/token",
      scopes: ["dashboards_read", "monitors_read"],
    },
  },
  {
    slug: "canva",
    name: "Canva",
    description:
      "Design content, brand assets, and marketing collateral workflows.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Canva",
    kind: "Design",
    tools: [],
    notes: "Broad creator and marketing adoption with OAuth-based apps.",
    categories: ["Design", "Marketing"],
    docsUrl: "https://www.canva.dev/docs/connect/oauth/",
    connectorProvider: "http",
    apiBaseUrl: "https://api.canva.com/rest/v1",
    openApiUrl:
      "https://raw.githubusercontent.com/canva-sdks/canva-connect-api-starter-kit/main/openapi/spec.yml",
    oauthConfig: {
      authorizationUrl: "https://www.canva.com/api/oauth/authorize",
      tokenUrl: "https://api.canva.com/rest/v1/oauth/token",
    },
  },
  {
    slug: "miro",
    name: "Miro",
    description: "Whiteboards, diagrams, notes, and workshop collaboration.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Miro",
    kind: "Whiteboard",
    tools: [],
    notes: "Strong visual collaboration target for design and product teams.",
    categories: ["Whiteboard", "Collaboration"],
    docsUrl: "https://developers.miro.com/docs/mcp-intro",
    logoUrl: "https://cdn.simpleicons.org/miro/05003B",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.miro.com/",
    oauthConfig: {
      authorizationUrl: "https://miro.com/oauth/authorize",
      tokenUrl: "https://api.miro.com/v1/oauth/token",
      scopes: ["boards:read"],
    },
  },
  {
    slug: "webflow",
    name: "Webflow",
    description: "CMS items, sites, and web publishing workflows.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Webflow",
    kind: "CMS",
    tools: [],
    notes:
      "Uses Webflow's official hosted MCP server and deployment-scoped MCP OAuth registration so each user can authorize their own sites and workspaces.",
    categories: ["CMS", "Marketing"],
    docsUrl: "https://developers.webflow.com/mcp/reference/getting-started",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.webflow.com/mcp",
    oauthConfig: {
      authorizationUrl: "https://mcp.webflow.com/oauth/authorize",
      tokenUrl: "https://mcp.webflow.com/oauth/token",
      clientAuthentication: "none",
      registrationUrl: "https://mcp.webflow.com/oauth/register",
    },
  },
  {
    slug: "zoom",
    name: "Zoom",
    description: "Meetings, recordings, webinars, and scheduling operations.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Zoom",
    kind: "Meetings",
    tools: [],
    notes: "Frequently requested for scheduling and meeting summaries.",
    categories: ["Meetings", "Calendar"],
    docsUrl: "https://developers.zoom.us/docs/integrations/oauth/",
    connectorProvider: "http",
    apiBaseUrl: "https://api.zoom.us/v2",
    openApiUrl: "https://api.apis.guru/v2/specs/zoom.us/2.0.0/openapi.json",
    oauthConfig: {
      authorizationUrl: "https://zoom.us/oauth/authorize",
      tokenUrl: "https://zoom.us/oauth/token",
      scopes: ["meeting:read:user"],
    },
  },
  {
    slug: "discord",
    name: "Discord",
    description: "Guilds, channels, messages, and community operations.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Discord",
    kind: "Communication",
    tools: [],
    notes: "Useful for community automation and bot-assisted workflows.",
    categories: ["Communication", "Community"],
    docsUrl: "https://discord.com/developers/docs/topics/oauth2",
    connectorProvider: "http",
    apiBaseUrl: "https://discord.com/api/v10",
    openApiUrl:
      "https://raw.githubusercontent.com/discord/discord-api-spec/main/specs/openapi.json",
    oauthConfig: {
      authorizationUrl: "https://discord.com/oauth2/authorize",
      tokenUrl: "https://discord.com/api/oauth2/token",
      scopes: ["identify", "guilds"],
    },
  },
  {
    slug: "stripe",
    name: "Stripe",
    description:
      "Query customers, payments, subscriptions, and invoices via Stripe's hosted MCP server.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Stripe",
    kind: "Payments",
    tools: [],
    notes: "High-value fintech automation target with mature OAuth patterns.",
    categories: ["Payments", "Finance"],
    docsUrl: "https://stripe.com/docs/mcp",
    logoUrl: "https://cdn.simpleicons.org/stripe/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.stripe.com/",
  },
  {
    slug: "intercom",
    name: "Intercom",
    description: "Customer support, conversations, inboxes, and CRM context.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Intercom",
    kind: "Support",
    tools: [],
    notes: "Useful for customer-facing assistant workflows.",
    categories: ["Support", "CRM"],
    docsUrl:
      "https://developers.intercom.com/building-apps/docs/authentication-types",
    connectorProvider: "http",
    apiBaseUrl: "https://api.intercom.io",
    openApiUrl:
      "https://raw.githubusercontent.com/intercom/Intercom-OpenAPI/main/descriptions/2.15/api.intercom.io.yaml",
    oauthConfig: {
      authorizationUrl: "https://app.intercom.com/oauth",
      tokenUrl: "https://api.intercom.io/auth/eagle/token",
      scopes: ["read_users", "read_conversations"],
    },
  },
  {
    slug: "hubspot",
    name: "HubSpot",
    description: "CRM, marketing, tickets, and customer lifecycle workflows.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "HubSpot",
    kind: "CRM",
    tools: [],
    notes:
      "Uses HubSpot's official remote MCP server plus MCP auth apps with PKCE.",
    categories: ["CRM", "Marketing"],
    docsUrl:
      "https://developers.hubspot.com/docs/apps/developer-platform/build-apps/integrate-with-the-remote-hubspot-mcp-server",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.hubspot.com",
    oauthConfig: {
      authorizationUrl: "https://mcp.hubspot.com/oauth/authorize/user",
      tokenUrl: "https://mcp.hubspot.com/oauth/v3/token",
      clientAuthentication: "body",
    },
  },
  {
    slug: "salesforce",
    name: "Salesforce",
    description: "CRM records, accounts, opportunities, and sales operations.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Salesforce",
    kind: "CRM",
    tools: [],
    notes: "Very common enterprise CRM and agent-assist target.",
    categories: ["CRM", "Sales"],
    docsUrl:
      "https://developer.salesforce.com/docs/platform/hosted-mcp-servers",
    logoUrl:
      "https://cdn.jsdelivr.net/gh/OpenHands/extensions/integrations/icons/salesforce.svg",
    connectorProvider: "mcp",
    serverUrl:
      "https://api.salesforce.com/platform/mcp/v1/platform/sobject-reads",
    oauthConfig: {
      authorizationUrl:
        "https://login.salesforce.com/services/oauth2/authorize",
      tokenUrl: "https://login.salesforce.com/services/oauth2/token",
      scopes: ["refresh_token"],
    },
  },
  {
    slug: "sharepoint",
    name: "SharePoint",
    description: "Sites, document libraries, lists, and intranet content.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "SharePoint",
    kind: "Knowledge base",
    tools: [],
    notes: "Frequently requested for enterprise knowledge retrieval.",
    categories: ["Knowledge base", "Enterprise"],
    docsUrl: "https://learn.microsoft.com/graph/auth-v2-user",
    connectorProvider: "http",
    apiBaseUrl: "https://graph.microsoft.com/v1.0",
    openApiUrl:
      "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
    oauthConfig: {
      authorizationUrl:
        "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
      tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
      scopes: ["Sites.Read.All"],
    },
  },
  {
    slug: "onedrive",
    name: "OneDrive",
    description:
      "Cloud file access and document workflows through Microsoft Graph.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "OneDrive",
    kind: "Storage",
    tools: [],
    notes: "Useful for enterprise file automation and search.",
    categories: ["Storage", "Documents"],
    docsUrl: "https://learn.microsoft.com/graph/auth-v2-user",
    connectorProvider: "http",
    apiBaseUrl: "https://graph.microsoft.com/v1.0",
    openApiUrl:
      "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
    oauthConfig: {
      authorizationUrl:
        "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
      tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
      scopes: ["Files.Read"],
    },
  },
  {
    slug: "microsoft-teams",
    name: "Microsoft Teams",
    description:
      "Chats, channels, meetings, and collaboration via Microsoft Graph.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Microsoft Teams",
    kind: "Communication",
    tools: [],
    notes: "Common enterprise chat target alongside Outlook.",
    categories: ["Communication", "Enterprise"],
    docsUrl: "https://learn.microsoft.com/graph/auth-v2-user",
    connectorProvider: "http",
    apiBaseUrl: "https://graph.microsoft.com/v1.0",
    openApiUrl:
      "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
    oauthConfig: {
      authorizationUrl:
        "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
      tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
      scopes: ["Team.ReadBasic.All"],
    },
  },
  {
    slug: "microsoft-outlook",
    name: "Microsoft Outlook",
    description:
      "Mail, calendar, contacts, and meeting workflows through Microsoft Graph.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Microsoft Outlook",
    kind: "Email",
    tools: [],
    notes:
      "High-value Microsoft Graph integration surface for enterprise users.",
    categories: ["Email", "Calendar"],
    docsUrl: "https://learn.microsoft.com/graph/auth-v2-user",
    connectorProvider: "http",
    apiBaseUrl: "https://graph.microsoft.com/v1.0",
    openApiUrl:
      "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
    oauthConfig: {
      authorizationUrl:
        "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
      tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
      scopes: ["Mail.Read"],
    },
  },
  {
    slug: "box",
    name: "Box",
    description: "Enterprise file storage, metadata, and collaboration.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Box",
    kind: "Storage",
    tools: [],
    notes: "Strong enterprise document-management footprint.",
    categories: ["Storage", "Enterprise"],
    docsUrl: "https://developer.box.com/guides/authentication/oauth2/",
    connectorProvider: "http",
    apiBaseUrl: "https://api.box.com/2.0",
    openApiUrl:
      "https://raw.githubusercontent.com/box/box-openapi/main/openapi.json",
    oauthConfig: {
      authorizationUrl: "https://account.box.com/api/oauth2/authorize",
      tokenUrl: "https://api.box.com/oauth2/token",
      scopes: ["root_readonly", "item_read"],
    },
  },
  {
    slug: "airtable",
    name: "Airtable",
    description:
      "List bases, query records, and update fields across your Airtable workspace.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Airtable",
    kind: "Database",
    tools: [],
    notes: "Very common internal-tools and operations automation surface.",
    categories: ["Database", "Operations"],
    docsUrl: "https://github.com/domdomegg/airtable-mcp-server",
    logoUrl: "https://cdn.simpleicons.org/airtable/000000",
    connectorProvider: "mcp",
  },
  {
    slug: "monday",
    name: "Monday.com",
    description: "Boards, automations, and work management across teams.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Monday.com",
    kind: "Project management",
    tools: [],
    notes: "High-demand operations platform with rich board APIs.",
    categories: ["Project management", "Operations"],
    docsUrl: "https://monday.com/w/mcp",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.monday.com/mcp",
    oauthConfig: {
      authorizationUrl: "https://auth.monday.com/oauth2/authorize",
      tokenUrl: "https://auth.monday.com/oauth2/token",
      scopes: ["boards:read"],
    },
  },
  {
    slug: "trello",
    name: "Trello",
    description: "Boards, cards, checklists, and lightweight project planning.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Trello",
    kind: "Project management",
    tools: [],
    notes:
      "Trello now uses Atlassian OAuth2 (auth.atlassian.com) for API authorization.",
    categories: ["Project management", "Operations"],
    docsUrl:
      "https://developer.atlassian.com/cloud/trello/guides/rest-api/authorization/",
    connectorProvider: "http",
    apiBaseUrl: "https://api.trello.com/1",
    openApiUrl: "https://developer.atlassian.com/cloud/trello/swagger.v3.json",
    oauthConfig: {
      authorizationUrl: "https://auth.atlassian.com/authorize",
      tokenUrl: "https://api.atlassian.com/oauth/token",
      scopes: ["read", "write"],
    },
  },
  {
    slug: "asana",
    name: "Asana",
    description: "Task management, projects, and work tracking.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Asana",
    kind: "Project management",
    tools: [],
    notes: "Broad business adoption and straightforward OAuth app model.",
    categories: ["Project management", "Operations"],
    docsUrl: "https://developers.asana.com/docs/oauth",
    connectorProvider: "http",
    apiBaseUrl: "https://app.asana.com/api/1.0",
    openApiUrl: "https://api.apis.guru/v2/specs/asana.com/1.0/openapi.json",
    oauthConfig: {
      authorizationUrl: "https://app.asana.com/-/oauth_authorize",
      tokenUrl: "https://app.asana.com/-/oauth_token",
      scopes: ["tasks:read"],
    },
  },
  {
    slug: "confluence",
    name: "Confluence",
    description: "Wiki pages, spaces, and internal documentation search.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Confluence",
    kind: "Documentation",
    tools: [],
    notes: "Natural companion to Jira for software teams.",
    categories: ["Documentation", "Knowledge base"],
    docsUrl:
      "https://developer.atlassian.com/cloud/confluence/oauth-2-3lo-apps/",
    connectorProvider: "http",
    apiBaseUrl: "https://api.atlassian.com/ex/confluence/{cloudId}",
    openApiUrl:
      "https://developer.atlassian.com/cloud/confluence/swagger.v3.json",
    oauthConfig: {
      authorizationUrl: "https://auth.atlassian.com/authorize",
      tokenUrl: "https://auth.atlassian.com/oauth/token",
      scopes: ["read:page:confluence"],
    },
  },
  {
    slug: "jira",
    name: "Jira",
    description:
      "Issue tracking, sprint workflows, and engineering program management.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Jira",
    kind: "Project management",
    tools: [],
    notes: "Very common MCP target for software teams and ticket automation.",
    categories: ["Project management", "Engineering"],
    docsUrl:
      "https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/",
    connectorProvider: "http",
    apiBaseUrl: "https://api.atlassian.com/ex/jira/{cloudId}",
    openApiUrl:
      "https://developer.atlassian.com/cloud/jira/platform/swagger.v3.json",
    oauthConfig: {
      authorizationUrl: "https://auth.atlassian.com/authorize",
      tokenUrl: "https://auth.atlassian.com/oauth/token",
      scopes: ["read:jira-work"],
    },
  },
  {
    slug: "google-calendar",
    name: "Google Calendar",
    description: "Calendar search, event scheduling, and meeting coordination.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Google Calendar",
    kind: "Calendar",
    tools: [],
    notes: "Strong personal productivity use case with mature OAuth flows.",
    categories: ["Calendar", "Scheduling"],
    docsUrl: "https://developers.google.com/identity/protocols/oauth2",
    connectorProvider: "http",
    apiBaseUrl: "https://www.googleapis.com/calendar/v3",
    openApiUrl:
      "https://api.apis.guru/v2/specs/googleapis.com/calendar/v3/openapi.json",
    oauthConfig: {
      authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scopes: ["https://www.googleapis.com/auth/calendar.readonly"],
    },
  },
  {
    slug: "gmail",
    name: "Gmail",
    description: "Mailbox search, drafting, sending, and thread triage.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Gmail",
    kind: "Communication",
    tools: [],
    notes: "Popular agent workflow target for inbox triage and drafting.",
    categories: ["Communication", "Email"],
    docsUrl: "https://developers.google.com/identity/protocols/oauth2",
    connectorProvider: "http",
    apiBaseUrl: "https://gmail.googleapis.com",
    openApiUrl:
      "https://api.apis.guru/v2/specs/googleapis.com/gmail/v1/openapi.json",
    oauthConfig: {
      authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scopes: ["https://www.googleapis.com/auth/gmail.readonly"],
    },
  },
  {
    slug: "google-sheets",
    name: "Google Sheets",
    description:
      "Spreadsheet reads, writes, formulas, and reporting workflows.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Google Sheets",
    kind: "Spreadsheets",
    tools: [],
    notes:
      "High-value automation surface for agent-driven reporting and structured edits.",
    categories: ["Spreadsheets", "Analytics"],
    docsUrl: "https://developers.google.com/identity/protocols/oauth2",
    connectorProvider: "http",
    apiBaseUrl: "https://sheets.googleapis.com",
    openApiUrl:
      "https://api.apis.guru/v2/specs/googleapis.com/sheets/v4/openapi.json",
    oauthConfig: {
      authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scopes: ["https://www.googleapis.com/auth/spreadsheets.readonly"],
    },
  },
  {
    slug: "google-drive",
    name: "Google Drive",
    description: "File search, metadata, folders, and document discovery.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Google Drive",
    kind: "Storage",
    tools: [],
    notes:
      "Natural expansion of the Google Workspace surface beyond Google Docs.",
    categories: ["Storage", "Documents"],
    docsUrl: "https://developers.google.com/identity/protocols/oauth2",
    connectorProvider: "http",
    apiBaseUrl: "https://www.googleapis.com/drive/v3",
    openApiUrl:
      "https://api.apis.guru/v2/specs/googleapis.com/drive/v3/openapi.json",
    oauthConfig: {
      authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scopes: ["https://www.googleapis.com/auth/drive.metadata.readonly"],
    },
  },
  {
    slug: "figma",
    name: "Figma",
    description:
      "Read Figma frames, components, and styles to ground UI work in your designs.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Figma",
    kind: "Design",
    tools: [],
    categories: ["Design", "Frontend"],
    docsUrl: "https://github.com/GLips/Figma-Context-MCP",
    logoUrl: "https://cdn.simpleicons.org/figma/FFFFFF",
    connectorProvider: "mcp",
  },
  {
    slug: "google-docs",
    name: "Google Docs",
    description: "Docs authoring and Google Workspace document automation.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Google Docs",
    kind: "Documents",
    tools: [],
    notes:
      "Current managed connector accepts a Google access token manually; a full OAuth connect flow can remove token copy/paste.",
    categories: ["Documents", "Knowledge base"],
    docsUrl: "https://developers.google.com/identity/protocols/oauth2",
    connectorProvider: "http",
    apiBaseUrl: "https://docs.googleapis.com",
    openApiUrl:
      "https://api.apis.guru/v2/specs/googleapis.com/docs/v1/openapi.json",
    oauthConfig: {
      authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scopes: ["https://www.googleapis.com/auth/documents.readonly"],
    },
  },
  {
    slug: "apify",
    name: "Apify Actors",
    description:
      "Run any of Apify's 5,000+ Actors (scrapers, automations) from the agent.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Apify Actors",
    kind: "Integration",
    tools: [],
    docsUrl: "https://docs.apify.com/platform/integrations/mcp",
    connectorProvider: "mcp",
  },
  {
    slug: "atlassian-rovo",
    name: "Atlassian Rovo",
    description:
      "Search, create, and update Jira issues, Confluence pages, Bitbucket repos, and Jira Service Management tickets - all through Atlassian's official hosted MCP server, powered by your Teamwork Graph.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Atlassian Rovo",
    kind: "Project management",
    tools: [],
    notes:
      "OAuth 2.1 is handled entirely by the Atlassian Rovo MCP server. No client credentials required - sign in with your Atlassian account when the authentication flow starts.",
    categories: ["Project management", "Documentation", "Engineering"],
    docsUrl:
      "https://support.atlassian.com/atlassian-rovo-mcp-server/docs/getting-started-with-the-atlassian-remote-mcp-server/",
    logoUrl: "https://cdn.simpleicons.org/atlassian/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.atlassian.com/v1/mcp/authv2",
    oauthConfig: { clientAuthentication: "none" },
  },
  {
    slug: "brave-search",
    name: "Brave Search",
    description:
      "Privacy-first web and local search using the Brave Search API.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Brave Search",
    kind: "Integration",
    tools: [],
    docsUrl: "https://github.com/brave/brave-search-mcp-server",
    logoUrl: "https://cdn.simpleicons.org/brave/FFFFFF",
    connectorProvider: "mcp",
  },
  {
    slug: "browser-mcp",
    name: "Browser MCP",
    description:
      "Control your local browser tab — navigate, click, type, and read DOM contents.",
    authStrategy: "none",
    toolCount: 0,
    provider: "Browser MCP",
    kind: "Integration",
    tools: [],
    docsUrl: "https://browsermcp.io/",
    connectorProvider: "mcp",
  },
  {
    slug: "clickhouse",
    name: "ClickHouse",
    description: "Run analytical SQL queries against a ClickHouse cluster.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "ClickHouse",
    kind: "Integration",
    tools: [],
    docsUrl: "https://github.com/ClickHouse/mcp-clickhouse",
    logoUrl: "https://cdn.simpleicons.org/clickhouse/000000",
    connectorProvider: "mcp",
  },
  {
    slug: "cloudflare-bindings",
    name: "Cloudflare Workers Bindings",
    description:
      "Inspect and manage KV, D1, R2, and Durable Object bindings on your Cloudflare account.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Cloudflare Workers Bindings",
    kind: "Integration",
    tools: [],
    docsUrl: "https://developers.cloudflare.com/agents/model-context-protocol/",
    logoUrl: "https://cdn.simpleicons.org/cloudflare/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://bindings.mcp.cloudflare.com/mcp",
  },
  {
    slug: "cloudflare-browser-rendering",
    name: "Cloudflare Browser Rendering",
    description:
      "Fetch and screenshot pages using Cloudflare's hosted browser rendering.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Cloudflare Browser Rendering",
    kind: "Integration",
    tools: [],
    docsUrl: "https://developers.cloudflare.com/agents/model-context-protocol/",
    logoUrl: "https://cdn.simpleicons.org/cloudflare/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://browser.mcp.cloudflare.com/mcp",
  },
  {
    slug: "cloudflare-builds",
    name: "Cloudflare Builds",
    description:
      "Inspect Workers Builds — logs, statuses, and rerun failed deploys.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Cloudflare Builds",
    kind: "Integration",
    tools: [],
    docsUrl: "https://developers.cloudflare.com/agents/model-context-protocol/",
    logoUrl: "https://cdn.simpleicons.org/cloudflare/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://builds.mcp.cloudflare.com/mcp",
  },
  {
    slug: "cloudflare-docs",
    name: "Cloudflare Docs",
    description:
      "Search and reference Cloudflare's developer documentation directly from the agent.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Cloudflare Docs",
    kind: "Integration",
    tools: [],
    docsUrl: "https://developers.cloudflare.com/agents/model-context-protocol/",
    logoUrl: "https://cdn.simpleicons.org/cloudflare/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://docs.mcp.cloudflare.com/mcp",
  },
  {
    slug: "cloudflare-observability",
    name: "Cloudflare Observability",
    description:
      "Tail Workers logs and query observability data from your Cloudflare account.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Cloudflare Observability",
    kind: "Integration",
    tools: [],
    docsUrl: "https://developers.cloudflare.com/agents/model-context-protocol/",
    logoUrl: "https://cdn.simpleicons.org/cloudflare/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://observability.mcp.cloudflare.com/mcp",
  },
  {
    slug: "deepwiki",
    name: "DeepWiki",
    description:
      "Ask grounded questions about any public GitHub repository via Devin's DeepWiki MCP.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "DeepWiki",
    kind: "Integration",
    tools: [],
    docsUrl: "https://docs.devin.ai/work-with-devin/deepwiki-mcp",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.deepwiki.com/mcp",
  },
  {
    slug: "everything",
    name: "Everything (demo)",
    description:
      "Reference server exercising every MCP capability — useful for testing.",
    authStrategy: "none",
    toolCount: 0,
    provider: "Everything (demo)",
    kind: "Integration",
    tools: [],
    docsUrl:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/everything",
    connectorProvider: "mcp",
  },
  {
    slug: "exa",
    name: "Exa",
    description:
      "Neural web search with semantic ranking, content extraction, and similar-page lookup.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Exa",
    kind: "Integration",
    tools: [],
    docsUrl: "https://docs.exa.ai/reference/exa-mcp",
    connectorProvider: "mcp",
  },
  {
    slug: "fetch",
    name: "Fetch",
    description:
      "Plain HTTP fetcher: download a URL and convert HTML to readable markdown.",
    authStrategy: "none",
    toolCount: 0,
    provider: "Fetch",
    kind: "Integration",
    tools: [],
    docsUrl:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
    connectorProvider: "mcp",
  },
  {
    slug: "filesystem",
    name: "Filesystem",
    description:
      "Give the agent secure, scoped filesystem access outside the workspace.",
    authStrategy: "none",
    toolCount: 0,
    provider: "Filesystem",
    kind: "Integration",
    tools: [],
    docsUrl:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    connectorProvider: "mcp",
  },
  {
    slug: "firecrawl",
    name: "Firecrawl",
    description:
      "Crawl any site and return clean markdown, structured data, or screenshots.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Firecrawl",
    kind: "Integration",
    tools: [],
    docsUrl: "https://docs.firecrawl.dev/mcp",
    connectorProvider: "mcp",
  },
  {
    slug: "git",
    name: "Git",
    description:
      "Local git repository operations: log, diff, blame, status, and more.",
    authStrategy: "none",
    toolCount: 0,
    provider: "Git",
    kind: "Integration",
    tools: [],
    docsUrl:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/git",
    connectorProvider: "mcp",
  },
  {
    slug: "huggingface",
    name: "Hugging Face",
    description:
      "Search models, datasets, and Spaces on the Hugging Face Hub from your agent.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Hugging Face",
    kind: "Integration",
    tools: [],
    docsUrl: "https://huggingface.co/docs/huggingface_hub/en/guides/mcp",
    logoUrl: "https://cdn.simpleicons.org/huggingface/000000",
    connectorProvider: "mcp",
    serverUrl: "https://huggingface.co/mcp",
  },
  {
    slug: "kagi",
    name: "Kagi Search",
    description:
      "Paid, privacy-first search with high signal-to-noise — great for research.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Kagi Search",
    kind: "Integration",
    tools: [],
    docsUrl: "https://github.com/kagisearch/kagimcp",
    logoUrl: "https://cdn.simpleicons.org/kagi/000000",
    connectorProvider: "mcp",
  },
  {
    slug: "memory",
    name: "Memory",
    description:
      "Persistent key-value memory for the agent across conversations.",
    authStrategy: "none",
    toolCount: 0,
    provider: "Memory",
    kind: "Integration",
    tools: [],
    docsUrl:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    connectorProvider: "mcp",
  },
  {
    slug: "mongodb",
    name: "MongoDB",
    description:
      "Query MongoDB collections, inspect schemas, and run aggregation pipelines.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "MongoDB",
    kind: "Integration",
    tools: [],
    docsUrl: "https://www.mongodb.com/docs/mcp-server/",
    logoUrl: "https://cdn.simpleicons.org/mongodb/FFFFFF",
    connectorProvider: "mcp",
  },
  {
    slug: "neon",
    name: "Neon",
    description:
      "Serverless Postgres: list projects, run queries, manage branches.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Neon",
    kind: "Integration",
    tools: [],
    docsUrl: "https://neon.com/docs/ai/neon-mcp-server",
    connectorProvider: "mcp",
  },
  {
    slug: "obsidian",
    name: "Obsidian",
    description:
      "Read and edit Markdown notes inside an Obsidian vault on the local disk.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Obsidian",
    kind: "Integration",
    tools: [],
    docsUrl: "https://github.com/MarkusPfundstein/mcp-obsidian",
    logoUrl: "https://cdn.simpleicons.org/obsidian/FFFFFF",
    connectorProvider: "mcp",
  },
  {
    slug: "paypal",
    name: "PayPal",
    description:
      "Manage transactions and merchant data via PayPal's MCP server.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "PayPal",
    kind: "Integration",
    tools: [],
    docsUrl: "https://developer.paypal.com/tools/mcp-server/",
    logoUrl: "https://cdn.simpleicons.org/paypal/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.paypal.com/mcp",
  },
  {
    slug: "playwright",
    name: "Playwright",
    description: "Headless-browser automation backed by Microsoft Playwright.",
    authStrategy: "none",
    toolCount: 0,
    provider: "Playwright",
    kind: "Integration",
    tools: [],
    docsUrl: "https://github.com/microsoft/playwright-mcp",
    connectorProvider: "mcp",
  },
  {
    slug: "redis",
    name: "Redis",
    description:
      "Get, set, scan, and inspect data on a Redis or Redis-compatible instance.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Redis",
    kind: "Integration",
    tools: [],
    docsUrl: "https://github.com/redis/mcp-redis",
    logoUrl: "https://cdn.simpleicons.org/redis/FFFFFF",
    connectorProvider: "mcp",
  },
  {
    slug: "resend",
    name: "Resend",
    description: "Send transactional and marketing emails via the Resend API.",
    authStrategy: "api_key",
    toolCount: 0,
    provider: "Resend",
    kind: "Integration",
    tools: [],
    docsUrl: "https://resend.com/docs/mcp",
    logoUrl: "https://cdn.simpleicons.org/resend/FFFFFF",
    connectorProvider: "mcp",
  },
  {
    slug: "sequential-thinking",
    name: "Sequential Thinking",
    description:
      "Lets the agent emit and revise a chain of structured thoughts.",
    authStrategy: "none",
    toolCount: 0,
    provider: "Sequential Thinking",
    kind: "Integration",
    tools: [],
    docsUrl:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    connectorProvider: "mcp",
  },
  {
    slug: "superhuman-mail",
    name: "Superhuman Mail",
    description:
      "Search, read, draft, and send email via Superhuman's hosted MCP server.",
    authStrategy: "oauth2",
    toolCount: 0,
    provider: "Superhuman Mail",
    kind: "Communication",
    tools: [],
    notes:
      "OAuth is handled by the Superhuman MCP server itself (mcp-remote). No client credentials required.",
    categories: ["Communication", "Email"],
    docsUrl: "https://github.com/superhuman/mcp-mail",
    logoUrl: "https://cdn.simpleicons.org/superhuman/FFFFFF",
    connectorProvider: "mcp",
    serverUrl: "https://mcp.mail.superhuman.com/mcp",
    oauthConfig: { clientAuthentication: "none" },
  },
  {
    slug: "time",
    name: "Time",
    description:
      "Timezone-aware current time, conversions, and timestamp formatting.",
    authStrategy: "none",
    toolCount: 0,
    provider: "Time",
    kind: "Integration",
    tools: [],
    docsUrl:
      "https://github.com/modelcontextprotocol/servers/tree/main/src/time",
    connectorProvider: "mcp",
  },
];
